name: Deploy to AWS EC2
# Force update

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # or your go version

      - name: Build Go Binary
        run: |
          cd backend
          go mod download
          GOOS=linux GOARCH=amd64 go build -o bot ./cmd/bot

      - name: Prepare Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo mkdir -p /opt/webtracker
            sudo chown -R ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} /opt/webtracker
            sudo chmod -R 755 /opt/webtracker

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "backend/bot,backend/webtracker-bot.service"
          target: "/opt/webtracker"
          strip_components: 1

      - name: Setup and Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Move service file to systemd directory
            sudo mv /opt/webtracker/webtracker-bot.service /etc/systemd/system/webtracker-bot.service
            
            # Set the correct user in the service file (replacing 'User=root' with actual user)
            sudo sed -i "s/User=root/User=${{ secrets.EC2_USER }}/g" /etc/systemd/system/webtracker-bot.service
            
            # Reload systemd and restart
            sudo systemctl daemon-reload
            sudo systemctl enable webtracker-bot
            sudo systemctl restart webtracker-bot
            sudo systemctl status webtracker-bot
